name: Deploy Analytics Service to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'services/analytics_service/**'
      - '.github/workflows/deploy-analytics-service.yml'

  # Allow manual trigger
  workflow_dispatch:

env:
  PROJECT_ID: aicfo
  SERVICE_NAME: delta-analytics-service
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Deploy Analytics Service
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --source . \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --memory 1Gi \
            --cpu 1 \
            --timeout 300 \
            --max-instances 5 \
            --min-instances 0 \
            --set-env-vars PYTHONPATH=/app,DATABASE_PATH=/app/web_ui/delta_transactions.db

      - name: Show deployment URL
        run: |
          URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --format="value(status.url)")
          echo "🚀 Analytics Service deployed at: $URL"
          echo "📊 API Endpoints available:"
          echo "  - $URL/api/analytics/monthly-summary"
          echo "  - $URL/api/analytics/entities"
          echo "  - $URL/api/analytics/categories"
          echo "  - $URL/api/analytics/dashboard"
          echo "  - $URL/api/analytics/status"

      - name: Test deployment
        run: |
          URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --format="value(status.url)")

          echo "Testing health endpoint..."
          curl -f $URL/ || echo "Health check failed"

          echo "Testing status endpoint..."
          curl -f $URL/api/analytics/status || echo "Status check failed"